### ISSUE TITLE
Cannot build from source

### ISSUE THREAD

**Issue by nderjung** [minotor-org/minotor#17]
Both configuration files for `qmake` and `make` (as required in the installation from source files) fail as a result of not being present:

```bash
$ qmake
qmake: could not find a Qt installation of ''
$ make
make: *** No targets specified and no makefile found. Stop.
```

**Comment by gotleg** [comment]
Did you have a look at : https://github.com/minotor-org/minotor/wiki/Install-(Linux) ?

**Comment by neomilium** [comment]
@gotleg these instructions are outdated.

@a1exanderjung your `qmake` message means you don't correctly installed Qt.
